apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swagger-service
  labels:
    app: swagger-service
    visualize: "true"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: swagger-service
  template:
    metadata:
      labels:
        app: swagger-service
        version: "v1"
        visualize: "true"
      annotations:
        visualizer/uses: eureka-server       
    spec:
      containers:
      - name: swagger-service
        image: gcr.io/appsutility-141503/swagger-service:v1
        imagePullPolicy: Always
        resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"        
        env:
        - name: EUREKA_URI
          value: http://eureka-server:8761
        - name: SERVICE_HOST_NAME
          value: swagger-service
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
        ports:
        - name: http
          containerPort: 8763

          
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-service
  labels:
    name: swagger-service
    visualize: "true"
spec:
  selector:
    app: swagger-service
  ports:
    - protocol: TCP
      port: 8763
      targetPort: 8763
  sessionAffinity: None
---


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: swagger-service
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: swagger-service
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50          