server:
  port: 8763

  context-path: /swagger

management:
  security:
    enabled: false
security:
  basic:
    enabled: false

---
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
      

---

spring:
  profiles: cloud
  

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}/eureka 
      
  instance: 
    preferIpAddress: true  