server:
  port: 8763

  context-path: /swagger-service

management:
  security:
    enabled: false
security:
  basic:
    enabled: false

---
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka

  instance: 
    hostname: localhost
    preferIpAddress: false        

---

spring:
  profiles: cloud
  

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}/eureka 
      
  instance: 
    hostname: ${SERVICE_HOST_NAME}
    preferIpAddress: false  